import type { Metadata } from "next";
import "./globals.css";
import localFont  from "next/font/local";

const montserrat = localFont({
  src: './montserrat-font/Montserrat-VariableFont_wght.ttf',
  variable: '--montserrat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased px-4`}
      >
        {children}
      </body>
    </html>
  );
}
